version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
      - ENVIRONMENT=dev
    restart: unless-stopped
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - app-network

volumes:
  server_project_files:

networks:
  app-network:
    driver: bridge
