version: "3.8"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: progchain
      POSTGRES_PASSWORD: progchain
      POSTGRES_DB: progchain
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U progchain"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
      - ENVIRONMENT=dev
      - DATABASE_URL=postgresql+asyncpg://progchain:progchain@db:5432/progchain
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - app-network

volumes:
  server_project_files:
  postgres_data:

networks:
  app-network:
    driver: bridge
